CREATE TABLE Cakes(
CakeID INT NOT NULL IDENTITY(1,1),
Price MONEY NOT NULL,
CakeWEIGHT FLOAT NOT NULL,
Discription NVARCHAR(70),
Composition NVARCHAR(70),
CONSTRAINT primary_Cake PRIMARY KEY (CakeID)
)